// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyvecudlwkaafwjbjcmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dmVjdWRsd2thYWZ3amJqY21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDY3NTAsImV4cCI6MjA2NzIyMjc1MH0.xRAfU4Aync3ETdLl92J9gETeE1ZAies04RZZFibs2ZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});